-- Government Benefits Sample Data
-- This script populates the government_benefits table with sample schemes for farmers

-- Crop Loss Compensation Schemes
INSERT INTO government_benefits (scheme_name, scheme_name_hindi, scheme_name_marathi, category, description, description_hindi, description_marathi, eligibility, eligibility_hindi, eligibility_marathi, benefits, benefits_hindi, benefits_marathi, how_to_apply, how_to_apply_hindi, how_to_apply_marathi, documents_required, documents_required_hindi, documents_required_marathi, official_website, helpline_number, state, is_active, created_at, updated_at)
VALUES 
('Pradhan Mantri Fasal Bima Yojana (PMFBY)', 'प्रधानमंत्री फसल बीमा योजना', 'प्रधानमंत्री पीक विमा योजना', 'CROP_LOSS', 
'Comprehensive crop insurance scheme providing financial support to farmers in case of crop loss due to natural calamities, pests, and diseases.', 
'प्राकृतिक आपदाओं, कीटों और बीमारियों के कारण फसल नुकसान की स्थिति में किसानों को वित्तीय सहायता प्रदान करने वाली व्यापक फसल बीमा योजना।',
'नैसर्गिक आपत्ती, कीटक आणि रोगांमुळे पीक नुकसान झाल्यास शेतकऱ्यांना आर्थिक मदत देणारी सर्वसमावेशक पीक विमा योजना।',
'All farmers including sharecroppers and tenant farmers growing notified crops in notified areas are eligible. Premium rates: Kharif 2%, Rabi 1.5%, Horticulture/Commercial crops 5%.',
'अधिसूचित क्षेत्रों में अधिसूचित फसलें उगाने वाले बटाईदार और किरायेदार किसान सहित सभी किसान पात्र हैं। प्रीमियम दरें: खरीफ 2%, रबी 1.5%, बागवानी/वाणिज्यिक फसलें 5%।',
'अधिसूचित क्षेत्रात अधिसूचित पिके घेणारे सर्व शेतकरी, भागीदार आणि भाडेकरू शेतकरी पात्र आहेत. प्रीमियम दर: खरीप 2%, रब्बी 1.5%, फळबाग/व्यावसायिक पिके 5%।',
'Sum insured equals to Scale of Finance for the crop. Difference between premium and actuarial rate is subsidized by Government. Claims settled within 2 months of crop loss assessment.',
'बीमा राशि फसल के लिए वित्त के पैमाने के बराबर है। प्रीमियम और बीमांकिक दर के बीच का अंतर सरकार द्वारा सब्सिडी दी जाती है। फसल नुकसान मूल्यांकन के 2 महीने के भीतर दावों का निपटान।',
'विमा रक्कम पिकासाठीच्या वित्त प्रमाणाच्या बरोबरीची आहे. प्रीमियम आणि वास्तविक दर यातील फरक सरकारद्वारे अनुदानित केला जातो. पीक नुकसान मूल्यांकनाच्या 2 महिन्यांत दाव्यांचे निकाल.',
'Apply through nearest bank branch, Common Service Centers (CSC), or online portal. Application must be submitted before sowing/planting season.',
'निकटतम बैंक शाखा, सामान्य सेवा केंद्र (CSC), या ऑनलाइन पोर्टल के माध्यम से आवेदन करें। बुवाई/रोपण सीजन से पहले आवेदन जमा करना होगा।',
'जवळच्या बँक शाखा, सामान्य सेवा केंद्र (CSC), किंवा ऑनलाइन पोर्टलद्वारे अर्ज करा. पेरणी/लागवड हंगामापूर्वी अर्ज सादर करणे आवश्यक आहे.',
'Land records (7/12, 8A), Aadhaar card, Bank account details, Sowing certificate from Patwari/Village Officer',
'भूमि रिकॉर्ड (7/12, 8A), आधार कार्ड, बैंक खाता विवरण, पटवारी/ग्राम अधिकारी से बुवाई प्रमाण पत्र',
'जमीन नोंदी (7/12, 8A), आधार कार्ड, बँक खाते तपशील, पटवारी/ग्राम अधिकारी यांचे पेरणी प्रमाणपत्र',
'https://pmfby.gov.in', '011-23382012', 'ALL_INDIA', true, NOW(), NOW()),

('Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)', 'प्रधानमंत्री किसान सम्मान निधि', 'प्रधानमंत्री किसान सन्मान निधी', 'SUBSIDY',
'Income support scheme providing ₹6000 per year in three equal installments to all landholding farmer families.',
'सभी भूमिधारक किसान परिवारों को तीन समान किस्तों में प्रति वर्ष ₹6000 प्रदान करने वाली आय सहायता योजना।',
'सर्व जमीनधारक शेतकरी कुटुंबांना तीन समान हप्त्यांमध्ये दरवर्षी ₹6000 देणारी उत्पन्न सहाय्य योजना।',
'All landholding farmer families having cultivable land. Institutional landholders, income tax payers, and government employees are excluded.',
'खेती योग्य भूमि वाले सभी भूमिधारक किसान परिवार। संस्थागत भूमिधारक, आयकर दाता और सरकारी कर्मचारी बाहर रखे गए हैं।',
'लागवडीयोग्य जमीन असलेली सर्व जमीनधारक शेतकरी कुटुंबे. संस्थात्मक जमीनधारक, आयकर भरणारे आणि सरकारी कर्मचारी वगळले आहेत.',
'₹2000 every 4 months directly transferred to bank account. Total ₹6000 per year. No upper limit on family size or land holding.',
'हर 4 महीने में ₹2000 सीधे बैंक खाते में स्थानांतरित। कुल ₹6000 प्रति वर्ष। परिवार के आकार या भूमि जोत पर कोई ऊपरी सीमा नहीं।',
'दर 4 महिन्यांनी ₹2000 थेट बँक खात्यात हस्तांतरित. एकूण ₹6000 दरवर्षी. कुटुंबाच्या आकारावर किंवा जमीन धारणावर कोणतीही वरची मर्यादा नाही.',
'Register online at pmkisan.gov.in or visit nearest Common Service Center. Aadhaar seeding with bank account is mandatory.',
'pmkisan.gov.in पर ऑनलाइन पंजीकरण करें या निकटतम सामान्य सेवा केंद्र पर जाएं। बैंक खाते के साथ आधार सीडिंग अनिवार्य है।',
'pmkisan.gov.in वर ऑनलाइन नोंदणी करा किंवा जवळच्या सामान्य सेवा केंद्राला भेट द्या. बँक खात्यासह आधार सीडिंग अनिवार्य आहे.',
'Aadhaar card, Land ownership documents, Bank account with Aadhaar seeding, Mobile number',
'आधार कार्ड, भूमि स्वामित्व दस्तावेज, आधार सीडिंग के साथ बैंक खाता, मोबाइल नंबर',
'आधार कार्ड, जमीन मालकी कागदपत्रे, आधार सीडिंगसह बँक खाते, मोबाइल नंबर',
'https://pmkisan.gov.in', '011-23381092', 'ALL_INDIA', true, NOW(), NOW()),

('Kisan Credit Card (KCC)', 'किसान क्रेडिट कार्ड', 'किसान क्रेडिट कार्ड', 'LOAN',
'Credit facility for farmers to meet short-term credit requirements for cultivation and other needs at concessional interest rates.',
'रियायती ब्याज दरों पर खेती और अन्य जरूरतों के लिए अल्पकालिक ऋण आवश्यकताओं को पूरा करने के लिए किसानों के लिए ऋण सुविधा।',
'सवलतीच्या व्याज दरांवर लागवड आणि इतर गरजांसाठी अल्पकालीन कर्ज आवश्यकता पूर्ण करण्यासाठी शेतकऱ्यांसाठी कर्ज सुविधा।',
'All farmers including tenant farmers, oral lessees, and sharecroppers. Fisheries and animal husbandry farmers also eligible.',
'किरायेदार किसानों, मौखिक पट्टेदारों और बटाईदारों सहित सभी किसान। मत्स्य पालन और पशुपालन किसान भी पात्र हैं।',
'भाडेकरू शेतकरी, तोंडी भाडेकरू आणि भागीदार यांसह सर्व शेतकरी. मत्स्यपालन आणि पशुसंवर्धन शेतकरी देखील पात्र आहेत.',
'Credit limit based on land holding and cropping pattern. Interest subvention of 2% for timely repayment. Additional 3% incentive for prompt payment. Effective interest rate can be as low as 4%.',
'भूमि जोत और फसल पैटर्न के आधार पर ऋण सीमा। समय पर चुकौती के लिए 2% ब्याज सब्वेंशन। त्वरित भुगतान के लिए अतिरिक्त 3% प्रोत्साहन। प्रभावी ब्याज दर 4% जितनी कम हो सकती है।',
'जमीन धारण आणि पीक पद्धतीवर आधारित कर्ज मर्यादा. वेळेवर परतफेडीसाठी 2% व्याज सवलत. त्वरित देयकासाठी अतिरिक्त 3% प्रोत्साहन. प्रभावी व्याज दर 4% इतका कमी असू शकतो.',
'Apply at nearest bank branch with required documents. Card issued within 15 days. Valid for 5 years with annual review.',
'आवश्यक दस्तावेजों के साथ निकटतम बैंक शाखा में आवेदन करें। 15 दिनों के भीतर कार्ड जारी। वार्षिक समीक्षा के साथ 5 साल के लिए वैध।',
'आवश्यक कागदपत्रांसह जवळच्या बँक शाखेत अर्ज करा. 15 दिवसांत कार्ड जारी. वार्षिक पुनरावलोकनासह 5 वर्षांसाठी वैध.',
'Land records, Identity proof, Address proof, Passport size photos',
'भूमि रिकॉर्ड, पहचान प्रमाण, पता प्रमाण, पासपोर्ट आकार की तस्वीरें',
'जमीन नोंदी, ओळख पुरावा, पत्ता पुरावा, पासपोर्ट आकाराचे फोटो',
'https://www.nabard.org/kcc.aspx', '1800-180-6999', 'ALL_INDIA', true, NOW(), NOW()),

('Maharashtra Crop Loss Compensation Scheme', 'महाराष्ट्र फसल नुकसान मुआवजा योजना', 'महाराष्ट्र पीक नुकसान भरपाई योजना', 'CROP_LOSS',
'State government scheme providing immediate relief to farmers affected by natural calamities like drought, flood, hailstorm, and unseasonal rains.',
'सूखा, बाढ़, ओलावृष्टि और बेमौसम बारिश जैसी प्राकृतिक आपदाओं से प्रभावित किसानों को तत्काल राहत प्रदान करने वाली राज्य सरकार की योजना।',
'दुष्काळ, पूर, गारपीट आणि अवकाळी पाऊस यासारख्या नैसर्गिक आपत्तींमुळे प्रभावित शेतकऱ्यांना तात्काळ मदत देणारी राज्य सरकारची योजना।',
'All farmers in Maharashtra with cultivable land affected by notified natural calamities. Both landowners and tenant farmers eligible.',
'अधिसूचित प्राकृतिक आपदाओं से प्रभावित खेती योग्य भूमि वाले महाराष्ट्र के सभी किसान। भूमि मालिक और किरायेदार किसान दोनों पात्र हैं।',
'अधिसूचित नैसर्गिक आपत्तींमुळे प्रभावित लागवडीयोग्य जमीन असलेले महाराष्ट्रातील सर्व शेतकरी. जमीन मालक आणि भाडेकरू शेतकरी दोन्ही पात्र आहेत.',
'Compensation up to ₹25,000 per hectare for crop loss above 33%. Additional ₹10,000 for complete crop loss. Payment within 60 days of damage assessment.',
'33% से अधिक फसल नुकसान के लिए प्रति हेक्टेयर ₹25,000 तक मुआवजा। पूर्ण फसल नुकसान के लिए अतिरिक्त ₹10,000। क्षति मूल्यांकन के 60 दिनों के भीतर भुगतान।',
'33% पेक्षा जास्त पीक नुकसानासाठी प्रति हेक्टर ₹25,000 पर्यंत भरपाई. संपूर्ण पीक नुकसानासाठी अतिरिक्त ₹10,000. नुकसान मूल्यांकनाच्या 60 दिवसांत देयक.',
'Submit application to Taluka Agriculture Officer within 72 hours of calamity. Joint inspection by revenue and agriculture officials.',
'आपदा के 72 घंटे के भीतर तालुका कृषि अधिकारी को आवेदन जमा करें। राजस्व और कृषि अधिकारियों द्वारा संयुक्त निरीक्षण।',
'आपत्तीच्या 72 तासांच्या आत तालुका कृषी अधिकाऱ्यांकडे अर्ज सादर करा. महसूल आणि कृषी अधिकाऱ्यांचे संयुक्त पाहणी.',
'7/12 extract, 8A extract, Aadhaar card, Bank passbook, Sowing certificate',
'7/12 उद्धरण, 8A उद्धरण, आधार कार्ड, बैंक पासबुक, बुवाई प्रमाण पत्र',
'7/12 उतारा, 8A उतारा, आधार कार्ड, बँक पासबुक, पेरणी प्रमाणपत्र',
'https://krishi.maharashtra.gov.in', '022-22025441', 'MAHARASHTRA', true, NOW(), NOW()),

('Soil Health Card Scheme', 'मृदा स्वास्थ्य कार्ड योजना', 'माती आरोग्य कार्ड योजना', 'SUBSIDY',
'Free soil testing and health card providing crop-wise recommendations on nutrients and fertilizers required for optimal crop yield.',
'इष्टतम फसल उपज के लिए आवश्यक पोषक तत्वों और उर्वरकों पर फसल-वार सिफारिशें प्रदान करने वाली मुफ्त मिट्टी परीक्षण और स्वास्थ्य कार्ड।',
'इष्टतम पीक उत्पादनासाठी आवश्यक पोषक तत्वे आणि खतांवर पीक-निहाय शिफारसी देणारी मोफत माती चाचणी आणि आरोग्य कार्ड.',
'All farmers across India. Priority given to small and marginal farmers. One card per farmer every 3 years.',
'भारत भर के सभी किसान। छोटे और सीमांत किसानों को प्राथमिकता। हर 3 साल में प्रति किसान एक कार्ड।',
'संपूर्ण भारतातील सर्व शेतकरी. लहान आणि सीमांत शेतकऱ्यांना प्राधान्य. दर 3 वर्षांनी प्रति शेतकरी एक कार्ड.',
'Free soil sample collection and testing. Detailed report on soil nutrients, pH, organic carbon. Crop-specific fertilizer recommendations. Digital and physical card provided.',
'मुफ्त मिट्टी नमूना संग्रह और परीक्षण। मिट्टी के पोषक तत्वों, pH, जैविक कार्बन पर विस्तृत रिपोर्ट। फसल-विशिष्ट उर्वरक सिफारिशें। डिजिटल और भौतिक कार्ड प्रदान किया गया।',
'मोफत माती नमुना संकलन आणि चाचणी. मातीतील पोषक तत्वे, pH, सेंद्रिय कार्बनवर तपशीलवार अहवाल. पीक-विशिष्ट खत शिफारसी. डिजिटल आणि भौतिक कार्ड प्रदान केले.',
'Contact nearest Krishi Vigyan Kendra or Agriculture Department office. Soil samples collected from your field. Card issued within 30 days.',
'निकटतम कृषि विज्ञान केंद्र या कृषि विभाग कार्यालय से संपर्क करें। आपके खेत से मिट्टी के नमूने एकत्र किए गए। 30 दिनों के भीतर कार्ड जारी।',
'जवळच्या कृषी विज्ञान केंद्र किंवा कृषी विभाग कार्यालयाशी संपर्क साधा. तुमच्या शेतातून माती नमुने गोळा केले. 30 दिवसांत कार्ड जारी.',
'Land records, Aadhaar card, Mobile number',
'भूमि रिकॉर्ड, आधार कार्ड, मोबाइल नंबर',
'जमीन नोंदी, आधार कार्ड, मोबाइल नंबर',
'https://soilhealth.dac.gov.in', '011-24305591', 'ALL_INDIA', true, NOW(), NOW()),

('Farm Mechanization Subsidy', 'कृषि यंत्रीकरण सब्सिडी', 'शेती यंत्रीकरण अनुदान', 'EQUIPMENT',
'Subsidy on purchase of agricultural machinery and equipment to promote farm mechanization and reduce labor costs.',
'कृषि यंत्रीकरण को बढ़ावा देने और श्रम लागत को कम करने के लिए कृषि मशीनरी और उपकरण की खरीद पर सब्सिडी।',
'शेती यंत्रीकरणाला प्रोत्साहन देण्यासाठी आणि श्रम खर्च कमी करण्यासाठी कृषी यंत्रसामग्री आणि उपकरणे खरेदीवर अनुदान.',
'All categories of farmers. SC/ST/Women farmers get higher subsidy. Small and marginal farmers prioritized.',
'किसानों की सभी श्रेणियां। SC/ST/महिला किसानों को अधिक सब्सिडी मिलती है। छोटे और सीमांत किसानों को प्राथमिकता।',
'शेतकऱ्यांच्या सर्व श्रेणी. SC/ST/महिला शेतकऱ्यांना जास्त अनुदान मिळते. लहान आणि सीमांत शेतकऱ्यांना प्राधान्य.',
'25-50% subsidy on tractors, power tillers, harvesters, sprayers, drip irrigation systems. Maximum subsidy limit varies by equipment. Direct benefit transfer to bank account.',
'ट्रैक्टर, पावर टिलर, हार्वेस्टर, स्प्रेयर, ड्रिप सिंचाई प्रणाली पर 25-50% सब्सिडी। अधिकतम सब्सिडी सीमा उपकरण के अनुसार भिन्न होती है। बैंक खाते में सीधा लाभ हस्तांतरण।',
'ट्रॅक्टर, पॉवर टिलर, हार्वेस्टर, फवारणी, ठिबक सिंचन प्रणालीवर 25-50% अनुदान. कमाल अनुदान मर्यादा उपकरणानुसार बदलते. बँक खात्यात थेट लाभ हस्तांतरण.',
'Apply online through state agriculture portal or visit District Agriculture Office. Submit quotations from authorized dealers. Subsidy released after purchase verification.',
'राज्य कृषि पोर्टल के माध्यम से ऑनलाइन आवेदन करें या जिला कृषि कार्यालय जाएं। अधिकृत डीलरों से उद्धरण जमा करें। खरीद सत्यापन के बाद सब्सिडी जारी।',
'राज्य कृषी पोर्टलद्वारे ऑनलाइन अर्ज करा किंवा जिल्हा कृषी कार्यालयाला भेट द्या. अधिकृत विक्रेत्यांकडून कोटेशन सादर करा. खरेदी पडताळणीनंतर अनुदान सोडले.',
'Land records, Aadhaar card, Bank account details, Quotations from dealers, Caste certificate (if applicable)',
'भूमि रिकॉर्ड, आधार कार्ड, बैंक खाता विवरण, डीलरों से उद्धरण, जाति प्रमाण पत्र (यदि लागू हो)',
'जमीन नोंदी, आधार कार्ड, बँक खाते तपशील, विक्रेत्यांकडून कोटेशन, जात प्रमाणपत्र (लागू असल्यास)',
'https://agrimachinery.nic.in', '011-23070964', 'ALL_INDIA', true, NOW(), NOW());

-- Made with Bob